In [17]:
import numpy

def matrix_factorization(R, P, Q, K, steps=5000, alpha=0.0002, beta=0.02):
    
    Q = Q.T
    
    for step in xrange(steps):
        for i in xrange(len(R)):
            for j in xrange(len(R[i])):
                if R[i][j] > 0:
                    eij = R[i][j] - numpy.dot(P[i,:],Q[:,j])
                    for k in xrange(K):
                        P[i][k] = P[i][k] + alpha * (2 * eij * Q[k][j] - beta * P[i][k])
                        Q[k][j] = Q[k][j] + alpha * (2 * eij * P[i][k] - beta * Q[k][j])
        eR = numpy.dot(P,Q)
        e = 0
        for i in xrange(len(R)):
            for j in xrange(len(R[i])):
                if R[i][j] > 0:
                    e = e + pow(R[i][j] - numpy.dot(P[i,:],Q[:,j]), 2)
                    # normalization
                    for k in xrange(K):
                        e = e + (beta/2) * (pow(P[i][k],2) + pow(Q[k][j],2))
        if step % 100 == 0:
            print "iteration",step,"error:",e
        if e < 0.001:
            break
    
    
    return P, Q.T


In [18]:
R = [
    [5,3,0,1],
    [4,0,0,1],
    [1,1,0,5],
    [1,0,0,4],
    [0,1,5,4],
]

R = numpy.array(R)

N = len(R)
M = len(R[0])
K = 3

P = numpy.random.rand(N,K) # user-latent matrix
Q = numpy.random.rand(M,K) # item-latent matrix

nP, nQ = matrix_factorization(R, P, Q, K, steps=10000)
nR = numpy.dot(nP, nQ.T)

iteration 0 error: 82.3618339348
iteration 100 error: 60.5750519946
iteration 200 error: 44.8458321227
iteration 300 error: 35.4508652198
iteration 400 error: 29.8323886003
iteration 500 error: 25.7903644191
iteration 600 error: 22.2151767539
iteration 700 error: 18.68981101
iteration 800 error: 15.172425838
iteration 900 error: 11.835455407
iteration 1000 error: 8.92758960138
iteration 1100 error: 6.63335937602
iteration 1200 error: 4.99094459795
iteration 1300 error: 3.9066529003
iteration 1400 error: 3.22800909781
iteration 1500 error: 2.81045326254
iteration 1600 error: 2.54753015178
iteration 1700 error: 2.37198997028
iteration 1800 error: 2.24527470865
iteration 1900 error: 2.14651292006
iteration 2000 error: 2.06469906237
iteration 2100 error: 1.99401988511
iteration 2200 error: 1.9313156269
iteration 2300 error: 1.87477371951
iteration 2400 error: 1.8232751681
iteration 2500 error: 1.77607024557
iteration 2600 error: 1.73261627208
iteration 2700 error: 1.69249454259
iteration 2

In [4]:
R

array([[5, 3, 0, 1],
       [4, 0, 0, 1],
       [1, 1, 0, 5],
       [1, 0, 0, 4],
       [0, 1, 5, 4]])

In [19]:
nR

array([[ 4.97813151,  2.97773525,  4.57866262,  1.00164119],
       [ 3.97965774,  2.36973846,  3.84246187,  0.9997563 ],
       [ 1.0219862 ,  0.94643827,  5.69738167,  4.96918894],
       [ 0.98939012,  0.82642272,  4.66483239,  3.97985017],
       [ 1.35846187,  1.06372278,  4.96619056,  4.00240827]])

In [6]:
nP,nQ

(array([[-0.25827397,  2.38136068],
        [-0.11245036,  1.85982849],
        [ 1.82778173,  0.81810458],
        [ 1.45250616,  0.68658217],
        [ 1.25475026,  1.45701111]]), array([[-0.33123109,  2.0881403 ],
        [-0.14150625,  1.144348  ],
        [ 1.13011239,  2.3552181 ],
        [ 2.41435452,  0.68244396]]))

In [9]:
numpy.dot(P[1,:],Q.T)

array([ 3.92082987,  2.14420344,  4.25322017,  0.99773368])